# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [ ]:
import numpy as np

2. Create a null vector of size 10 

In [15]:
# import numpy as np

x = np.zeros(10)
print(x)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a vector with values ranging from 10 to 49

In [22]:
x1=np.arange(10,50)
# print(x1)

4. Find the shape of previous array in question 3

In [20]:
x1.shape

(40,)

5. Print the type of the previous array in question 3

In [26]:
print(x1.dtype)

int32


6. Print the numpy version and the configuration


In [ ]:
print(np.version.version)
print(np.show_config())

7. Print the dimension of the array in question 3


In [27]:
x1.ndim

1

8. Create a boolean array with all the True values

In [30]:
x2=np.array([True,True,True])
print(x2)

[ True  True  True]


9. Create a two dimensional array




In [34]:
x3=np.array([[1,2,3],[4,5,6]])
print(x3)

[[1 2 3]
 [4 5 6]]


10. Create a three dimensional array



In [35]:
x4=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(x4)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [38]:
x5=x1[-1::-1]
print(x5)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


12. Create a null vector of size 10 but the fifth value which is 1 

In [40]:
x6=np.zeros(10)
x6[4]=1
print(x6)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [41]:
x7=np.eye(3,3)
print(x7)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [50]:
arr = np.array([1, 2, 3, 4, 5])*1.0
print(arr.dtype)

float64


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [48]:
arr1 = np.array([[1., 2., 3.],

[4., 5., 6.]])
arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])
print(arr1*arr2)


[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [52]:
x9=(arr1==arr2)
print(x9)

[[False False False]
 [False False False]]


17. Extract all odd numbers from arr with values(0-9)

In [59]:
arr=np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [61]:
for i in len:
    if(i%2==1):
        =-1
arr        
        

IndexError: index 5 is out of bounds for axis 0 with size 5

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [62]:
na=np.arange(0,15)
na[5]=12
na[6]=12
na[7]=12
na[8]=12
na

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9, 10, 11, 12, 13, 14])

20. Create a 2d array with 1 on the border and 0 inside

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [ ]:
arr2d = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
arr2d[1][1]=12
arr2d

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [ ]:
arr3d = np.array([[[1, 2, 3*64.0], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0]=64
arr3d


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [ ]:

arr2d=np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr2d[0][0:5]

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [ ]:
arr2d=np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr2d[1][1]

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [ ]:
t_d=np.array([[0,1,2,3,4],[5,6,7,8,9]])
print(t_d)
print('\n',t_d[:3:,2])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [ ]:

r_a=np.random.randint((10,10))
a=[10,8,9]
b=[5,4,3]
print('random numbers are ',r_a)
print(r_a.max())
print(r_a.min())

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [ ]:
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.unique((a,b))

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(data)
print('\n',data[names!="Will"])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [ ]:
data = np.random.randn(7, 4)
data[names=="Bob"]

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [ ]:
t_d=np.arange(1,16).reshape(5,3)
t_d

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [ ]:
t_d=np.arange(1,17,1).reshape(2,2,4)
t_d

33. Swap axes of the array you created in Question 32

In [ ]:
t_d[0][1]=t_d[1][0]
t_d

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [ ]:
s=np.random.randint(10)
print(s)
print(np.sqrt(s))
print(np.where(s<0.5,0,1))

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [ ]:

ar1=np.array(np.random.rand(12))
ar2=np.array(np.random.rand(12))
print('\n',ar1)
print('\n',ar2)
print('\n',np.where(ar1>ar2,ar1,ar2))
print('\n',np.where(ar2>ar1,ar2,ar1))

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print(a!=b)
print('\n',np.setdiff1d(a,b))

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [ ]:
sampleArray=np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
print(sampleArray)
print('\n',sampleArray[:,:2])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [ ]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

40. Generate a matrix of 20 random values and find its cumulative sum

In [ ]:
r=np.random.randn(20)
print(r)
print('\n',r.cumsum())